"""empty message

Revision ID: 1099e13a0e78
Revises: 960e73b17612
Create Date: 2020-07-07 19:44:29.952809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1099e13a0e78'
down_revision = '960e73b17612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirm_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirm_password', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
